spring.application.name=shms

# MongoDB Bindings explicitly mapping URI natively bypassing YAML execution silently
spring.data.mongodb.uri=mongodb+srv://admin:u5O0z1uOm3EGqOfq@cluster0.kze2bw9.mongodb.net/shms?appName=Cluster0

# JWT Structure mapping tokens explicitly
jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
jwt.expirationMs=86400000
